CREATE TABLE IF NOT EXISTS users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(50) NOT NULL,
    email      VARCHAR(32) NOT NULL,

    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
   id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name        VARCHAR(255) NOT NULL,
   description VARCHAR(255) NOT NULL,
   available   BOOLEAN,
   owner_id    BIGINT NOT NULL,
   request_id  BIGINT,

   FOREIGN KEY (request_id) REFERENCES request (id),
   CONSTRAINT fk_items_owner_id FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS bookings (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  start_date  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  end_date    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  item_id     BIGINT NOT NULL,
  booker_id   BIGINT NOT NULL,
  status      VARCHAR(16),

  CONSTRAINT fk_bookings_item_id FOREIGN KEY (item_id) REFERENCES items (id),
  CONSTRAINT fk_bookings_booker_id FOREIGN KEY (booker_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS requests (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description  VARCHAR(255) NOT NULL,
  requestor_id BIGINT, -- NOT NULL,

  --FOREIGN KEY requestor_id REFERENCES users (id)
  CONSTRAINT fk_request_requestor_id FOREIGN KEY (requestor_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS comments (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text        VARCHAR(1000) NOT NULL,
  item_id     BIGINT NOT NULL,
  author_id   BIGINT NOT NULL,


  CONSTRAINT fk_comments_item_ид FOREIGN KEY (item_id) REFERENCES items (id),
  CONSTRAINT fk_items_author_id FOREIGN KEY (author_id) REFERENCES users (id)
);
